# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waterana.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1676, 1166)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.CardWidget = CardWidget(self.centralwidget)
        self.CardWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.CardWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 60))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.PushButton = PushButton(self.CardWidget)
        self.PushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.PushButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.PushButton.setObjectName("PushButton")
        self.verticalLayout.addWidget(self.PushButton)
        self.PushButton_2 = PushButton(self.CardWidget)
        self.PushButton_2.setMinimumSize(QtCore.QSize(0, 60))
        self.PushButton_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.PushButton_2.setObjectName("PushButton_2")
        self.verticalLayout.addWidget(self.PushButton_2)
        self.PushButton_3 = PushButton(self.CardWidget)
        self.PushButton_3.setMinimumSize(QtCore.QSize(0, 60))
        self.PushButton_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.PushButton_3.setObjectName("PushButton_3")
        self.verticalLayout.addWidget(self.PushButton_3)
        self.PushButton_5 = PushButton(self.CardWidget)
        self.PushButton_5.setMinimumSize(QtCore.QSize(0, 60))
        self.PushButton_5.setObjectName("PushButton_5")
        self.verticalLayout.addWidget(self.PushButton_5)
        self.PushButton_4 = PushButton(self.CardWidget)
        self.PushButton_4.setMinimumSize(QtCore.QSize(0, 60))
        self.PushButton_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.PushButton_4.setObjectName("PushButton_4")
        self.verticalLayout.addWidget(self.PushButton_4)
        self.PushButton_6 = PushButton(self.CardWidget)
        self.PushButton_6.setMinimumSize(QtCore.QSize(0, 60))
        self.PushButton_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.PushButton_6.setObjectName("PushButton_6")
        self.verticalLayout.addWidget(self.PushButton_6)
        self.gridLayout.addWidget(self.CardWidget, 1, 0, 1, 1)
        self.CardWidget_2 = CardWidget(self.centralwidget)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout.addWidget(self.CardWidget_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.CardWidget_3 = CardWidget(self.centralwidget)
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.gridLayout.addWidget(self.CardWidget_3, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1676, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "初始化面板"))
        self.PushButton.setText(_translate("MainWindow", "数据导入"))
        self.PushButton_2.setText(_translate("MainWindow", "趋势分析"))
        self.PushButton_3.setText(_translate("MainWindow", "突变分析"))
        self.PushButton_5.setText(_translate("MainWindow", "周期分析"))
        self.PushButton_4.setText(_translate("MainWindow", "遭遇分析"))
        self.PushButton_6.setText(_translate("MainWindow", "归因分析"))
        self.label.setText(_translate("MainWindow", "水情分析"))
from qfluentwidgets import CardWidget, PushButton
